// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package jobsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    job_id,
    job_type,
    scope_type,
    scope_id,
    status,
    priority,
    payload
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING job_id, job_type, scope_type, scope_id, status, priority, payload, result, error, created_at, started_at, finished_at
`

type CreateJobParams struct {
	JobID     pgtype.UUID
	JobType   string
	ScopeType string
	ScopeID   string
	Status    string
	Priority  int32
	Payload   []byte
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.JobID,
		arg.JobType,
		arg.ScopeType,
		arg.ScopeID,
		arg.Status,
		arg.Priority,
		arg.Payload,
	)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.JobType,
		&i.ScopeType,
		&i.ScopeID,
		&i.Status,
		&i.Priority,
		&i.Payload,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT job_id, job_type, scope_type, scope_id, status, priority, payload, result, error, created_at, started_at, finished_at
FROM jobs
WHERE job_id = $1
LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, jobID pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, jobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.JobType,
		&i.ScopeType,
		&i.ScopeID,
		&i.Status,
		&i.Priority,
		&i.Payload,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
