// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package jobsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	JobID      pgtype.UUID
	JobType    string
	ScopeType  string
	ScopeID    string
	Status     string
	Priority   int32
	Payload    []byte
	Result     []byte
	Error      pgtype.Text
	CreatedAt  pgtype.Timestamptz
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type JobLog struct {
	ID        int64
	JobID     pgtype.UUID
	JobRunID  pgtype.UUID
	Seq       int64
	Level     string
	Message   string
	CreatedAt pgtype.Timestamptz
}

type JobRun struct {
	JobRunID   pgtype.UUID
	JobID      pgtype.UUID
	WorkerID   string
	Attempt    int32
	Status     string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}
